services:
  node1:
    build: .
    hostname: node1
    environment:
      - SERVER_PORT=8080
      - KVSTORE_NODES=http://node1:8080,http://node2:8080,http://node3:8080
      - KVSTORE_CURRENT_NODE_URL=http://node1:8080
    ports:
      - "8081:8080"

  node2:
    build: .
    hostname: node2
    environment:
      - SERVER_PORT=8080
      - KVSTORE_NODES=http://node1:8080,http://node2:8080,http://node3:8080
      - KVSTORE_CURRENT_NODE_URL=http://node2:8080
    ports:
      - "8082:8080"

  node3:
    build: .
    hostname: node3
    environment:
      - SERVER_PORT=8080
      - KVSTORE_NODES=http://node1:8080,http://node2:8080,http://node3:8080
      - KVSTORE_CURRENT_NODE_URL=http://node3:8080
    ports:
      - "8083:8080"
