spring:
  application:
    name: file-storage-s3
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

s3:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: my-files
  region: us-east-1
