services:
  crawler-node-1:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - HAZELCAST_MEMBERS=crawler-node-1,crawler-node-2
    networks:
      - crawler-net

  crawler-node-2:
    build: .
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - HAZELCAST_MEMBERS=crawler-node-1,crawler-node-2
    networks:
      - crawler-net
    depends_on:
      - crawler-node-1

networks:
  crawler-net:
    driver: bridge
